---
title: "Data Wrangling Final"
author: "f0040sz"
date: "11/19/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# libraries
library(dplyr)
library(RODBC)
library(lubridate)
```

```{r}
# load dataset
setwd("~/Desktop/QBS/Fall 2/Data Wrangling")
raw_data <- read.csv("IC_BP_v2.csv")
```

## 1)
### a)
```{r}
# change name of BPAlerts column
names(raw_data)[names(raw_data)=="BPAlerts"] <-"BPstatus"

sample_n(raw_data, 10)
```

### b)
```{r}
# create empty column to populate with 0 and 1
raw_data$controlledBP <- NA

# create conditions variables
normal <- c("Normal", "Hypo1")
nonNormal <- c("Hypo2", "HTN1", "HTN2", "HTN3")

# loop through rows to determine if participant has controlled or uncontrolled blood pressure
for(i in 1:nrow(raw_data)) {
  if(is.null(raw_data$BPstatus[i])) {
    next
  }
  if(raw_data$BPstatus[i] %in% normal) {
    raw_data$controlledBP[i] <- 1
  }
  else if(raw_data$BPstatus[i] %in% nonNormal) {
    raw_data$controlledBP[i] <- 0
  }
}

sample_n(raw_data, 10)
```

### c)
```{r}
# open SQL database connection
myConn <- odbcConnect("qbs 181", "pschuld",
                      "pschuld@qbs181")

# import datasets
demo <- sqlQuery(myConn, "select * from Demographics")

# merge datasents on contact id number
merged <- dplyr::inner_join(raw_data, demo, by = c("ID" = "contactid"))

sample_n(merged, 10)
```

### d)
```{r}
# extract first row for each ID as baseline values
baseline <- merged %>%
  group_by(ID) %>%
  slice(1) %>%
  select(ID, SystolicValue, Diastolicvalue, ObservedTime, controlledBP)

# add baseline indicator column 
baseline$time_point <- "baseline"

# extract all non-baseline values and average them by each ID
follow_up <- merged %>%
  group_by(ID) %>%
  slice(seq(from = 2,to = n())) %>%
  summarise(SystolicValue = mean(SystolicValue), Diastolicvalue = mean(Diastolicvalue), 
            ObservedTime  = mean(ObservedTime), controlledBP = round(mean(controlledBP, na.rm = TRUE)))

# add follow up indicator columns
follow_up$time_point <- "follow up"

# combine baseline and follow up to get baseline and 12-week values
baseline_follow_up <- rbind(data.frame(baseline), data.frame(follow_up))
baseline_follow_up <- baseline_follow_up %>% 
  arrange(ID, time_point)
```

### e)
```{r}
# summary statistics for baseline and follow-up scoring
print(paste("Average Baseline Systolic BP:", round(mean(baseline_follow_up$SystolicValue[baseline_follow_up$time_point == "baseline"], na.rm = TRUE))))
print(paste("Average Follow-Up Systolic BP:", round(mean(baseline_follow_up$SystolicValue[baseline_follow_up$time_point == "follow up"], na.rm = TRUE))))
print(paste("Average Baseline Diastolic BP:", round(mean(baseline_follow_up$Diastolicvalue[baseline_follow_up$time_point == "baseline"], na.rm = TRUE))))
print(paste("Average Follow-Up Diastolic BP:", round(mean(baseline_follow_up$Diastolicvalue[baseline_follow_up$time_point == "follow up"], na.rm = TRUE))))
print(paste("Average Baseline Observed Time:", round(mean(baseline_follow_up$ObservedTime[baseline_follow_up$time_point == "baseline"], na.rm = TRUE))))
print(paste("Average Follow-Up Observed Time:", round(mean(baseline_follow_up$ObservedTime[baseline_follow_up$time_point == "follow up"], na.rm = TRUE))))
```

### f)
```{r}
# extract IDs of those with uncontrolled BP at baseline
uncontrolled_id <- baseline_follow_up$ID[baseline_follow_up$controlledBP == 0 & 
                                           baseline_follow_up$time_point == "baseline"]

# extract IDs of those with controlled BP at follow up
controlled_id <- baseline_follow_up$ID[baseline_follow_up$controlledBP == 1 & 
                                           baseline_follow_up$time_point == "follow up"]

# sum shared IDs
paste(sum(controlled_id %in% uncontrolled_id), "individuals went from uncontrolled BP at baseline to controlled BP at follow up")
```


## 3)
```{r}
# load tabls from sql
cond <- sqlQuery(myConn, "select * from Conditions")
text <- sqlQuery(myConn, "select * from Text")

# merge three tables
merged_2 <- merge(demo, cond, by.x = "contactid", by.y = "tri_patientid")
merged_2 <- merge(merged_2, text, by.x = "contactid", by.y = "tri_contactId")

# remove row with latest text sent data for each contactid
latest_text <- merged_2 %>%
  group_by(contactid) %>%
  slice(which.min(TextSentDate))

print(latest_text[sample(nrow(latest_text), 10), ])
```





